# workflow name
name: Generate release-artifacts

# on events
on: push

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: install
      - run: sudo apt install -y mingw-w64
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'backend/'
            name: 'program'
            compress: 'true'
            dest: 'dist'
        env:
          CGO_ENABLED: "1" 
          CC: "x86_64-w64-mingw32-gcc"
          CGO_CFLAGS_ALLOW: "-Xpreprocessor"
